#!/usr/bin/env node
/**
 * scripts/update-docs.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Auto-documentation updater.
 *
 * What it does:
 *   1. Scans src/renderer/components/ to discover all component directories
 *   2. Scans src/renderer/context/   to discover context providers
 *   3. Scans src/renderer/hooks/     to discover custom hooks
 *   4. Rewrites docs/architecture.mmd with an up-to-date Mermaid diagram
 *   5. Rewrites docs/architecture.md  with a human-readable architecture guide
 *
 * Run manually:  npm run update-docs
 * Run in CI:     Triggered automatically by .github/workflows/update-docs.yml
 *                on every push to the main branch.
 *
 * Exit codes:
 *   0 – success (files written)
 *   1 – error   (see stderr)
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

// ── Path resolution ───────────────────────────────────────────────────────────

const __filename  = fileURLToPath(import.meta.url);
const __dirname   = dirname(__filename);
const ROOT        = resolve(__dirname, '..');

const COMPONENTS_DIR = join(ROOT, 'src', 'renderer', 'components');
const CONTEXT_DIR    = join(ROOT, 'src', 'renderer', 'context');
const HOOKS_DIR      = join(ROOT, 'src', 'renderer', 'hooks');
const DOCS_DIR       = join(ROOT, 'docs');
const MMD_FILE       = join(DOCS_DIR, 'architecture.mmd');
const MD_FILE        = join(DOCS_DIR, 'architecture.md');

// ── Discovery helpers ─────────────────────────────────────────────────────────

/**
 * Return the names of all subdirectories inside `dir`.
 * Each subdirectory is treated as one component/context/hook.
 */
function discoverDirs(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(name =>
    statSync(join(dir, name)).isDirectory()
  );
}

/**
 * Return the names of all .js/.jsx files inside `dir` (non-recursive).
 * Excludes test files (.test.js / .test.jsx / .spec.js) because they are not
 * modules and their names (e.g. "TaskContext.test") contain dots which are
 * invalid as Mermaid node identifiers.
 */
function discoverFiles(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(name => {
    if (!name.endsWith('.js') && !name.endsWith('.jsx')) return false;
    if (name.startsWith('.')) return false;
    if (name.includes('.test.') || name.includes('.spec.')) return false;
    return true;
  });
}

/**
 * Attempt to read the first JSDoc comment from a file and extract the
 * one-line summary (the text after the opening `/**`).
 */
function extractSummary(filePath) {
  try {
    const content = readFileSync(filePath, 'utf8');
    // Match /** ... *\/ and grab the first non-empty line
    const match = content.match(/\/\*\*[\s\S]*?\*\//);
    if (!match) return '';
    const lines = match[0]
      .split('\n')
      .map(l => l.replace(/^\s*\*+\s?/, '').trim())
      .filter(Boolean);
    // Skip the filename line (starts with "src/")
    const summary = lines.find(l => !l.startsWith('src/') && l.length > 5);
    return summary ?? '';
  } catch {
    return '';
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  console.log('🔍 Scanning project structure…\n');

  // ── Discover ──────────────────────────────────────────────────────────────
  const components = discoverDirs(COMPONENTS_DIR);
  const contexts   = discoverFiles(CONTEXT_DIR).map(f => f.replace(/\.(jsx|js)$/, ''));
  const hooks      = discoverFiles(HOOKS_DIR).map(f => f.replace(/\.(jsx|js)$/, ''));

  console.log(`  📦 Components : ${components.join(', ') || 'none'}`);
  console.log(`  🗃️  Contexts   : ${contexts.join(', ')   || 'none'}`);
  console.log(`  🪝 Hooks      : ${hooks.join(', ')       || 'none'}`);
  console.log();

  const timestamp = new Date().toISOString();

  // ── Generate architecture.mmd ─────────────────────────────────────────────
  const compNodes  = components.map(c => `        ${c}["🧩 ${c}"]`).join('\n');
  const ctxNodes   = contexts.map(c =>   `        ${c}["🗃️ ${c}"]`).join('\n');
  const hookNodes  = hooks.map(h =>      `        ${h}["🪝 ${h}"]`).join('\n');

  const compEdges  = components.map(c => `    App --> ${c}`).join('\n');
  const ctxEdges   = components.map(c => `    ${c} -.->|"useTasks / context"| TaskContext`).join('\n');

  const mmd = `\
%% ─────────────────────────────────────────────────────────────────────────────
%% DevBoard — Architecture Diagram
%% Auto-generated by scripts/update-docs.js — DO NOT EDIT MANUALLY
%% Last updated: ${timestamp}
%% Components: ${components.length} | Contexts: ${contexts.length} | Hooks: ${hooks.length}
%% ─────────────────────────────────────────────────────────────────────────────

graph TB
    subgraph Electron["Electron Shell"]
        Main["⚙️ Main Process\\nsrc/main/index.js"]
        Preload["🔒 Preload\\nsrc/main/preload.js"]
    end

    subgraph ReactApp["React Renderer"]
        Entry["📦 main.jsx"]
        App["🏠 App.jsx"]

        subgraph Components["UI Components (${components.length} total)"]
${compNodes}
        end

${contexts.length > 0 ? `        subgraph Contexts["State / Context"]
${ctxNodes}
        end` : ''}

${hooks.length > 0 ? `        subgraph Hooks["Custom Hooks"]
${hookNodes}
        end` : ''}
    end

    subgraph Storage["Persistence"]
        LS["💾 localStorage"]
    end

    Main --> ReactApp
    Main <--> Preload
    Preload -->|"window.electronAPI"| App
    Entry --> App
${compEdges}
${contexts.length > 0 ? ctxEdges : ''}
${contexts.length > 0 ? `    TaskContext -->|"persist"| LS` : ''}

    classDef electron fill:#1e3a5f,stroke:#4a90d9,color:#fff
    classDef react fill:#20232a,stroke:#61dafb,color:#61dafb
    classDef context fill:#2d1b69,stroke:#9c6ade,color:#fff
    classDef storage fill:#1a3a2a,stroke:#3fb950,color:#fff

    class Main,Preload electron
    class Entry,App,${components.join(',')} react
${contexts.length > 0 ? `    class ${contexts.join(',')} context` : ''}
    class LS storage
`;

  writeFileSync(MMD_FILE, mmd, 'utf8');
  console.log(`✅ Written: docs/architecture.mmd`);

  // ── Generate architecture.md ──────────────────────────────────────────────

  // Collect summaries for each component
  const componentTable = components.map(c => {
    const filePath = join(COMPONENTS_DIR, c, `${c}.jsx`);
    const summary  = extractSummary(filePath);
    return `| \`${c}\` | ${summary || '—'} |`;
  }).join('\n');

  const md = `# DevBoard — Architecture Guide

> Auto-generated by \`scripts/update-docs.js\`
> Last updated: \`${timestamp}\`
> Do not edit this file manually — run \`npm run update-docs\` to regenerate.

---

## Overview

DevBoard is an **Electron + React** desktop application that demonstrates:

- React as a UI framework for desktop apps via Electron
- CSS Modules for component-scoped styling with a shared design-token system
- React Context + useReducer for predictable state management (no Redux)
- HTML5 Drag and Drop API for inter-column task movement
- A contextBridge-based IPC pattern for secure Electron ↔ React communication
- Auto-generated architecture docs and Mermaid diagrams on every commit

---

## Process Architecture

\`\`\`
┌──────────────────────────────────────────────────────────┐
│  Electron Main Process  (src/main/index.js)              │
│  • Creates BrowserWindow                                 │
│  • Registers IPC handlers (version, theme, window ctrl) │
│  • Manages app lifecycle                                 │
└──────────────────────┬───────────────────────────────────┘
                       │ loads
┌──────────────────────▼───────────────────────────────────┐
│  Preload Script  (src/main/preload.js)                   │
│  • contextBridge.exposeInMainWorld → window.electronAPI │
│  • Safe, typed API surface for the renderer              │
└──────────────────────┬───────────────────────────────────┘
                       │ exposes API
┌──────────────────────▼───────────────────────────────────┐
│  React Renderer  (src/renderer/)                         │
│  • Vite + HMR in dev, static dist/ in production        │
│  • Full React component tree, no Node.js access          │
└──────────────────────────────────────────────────────────┘
\`\`\`

---

## Component Inventory (${components.length} components)

| Component | Description |
|-----------|-------------|
${componentTable}

---

## State Management

**TaskContext** (\`src/renderer/context/TaskContext.jsx\`) is the single source of truth for all task data.

- Uses \`React.createContext\` + \`useReducer\` — no external state library
- **Actions**: \`ADD_TASK\`, \`UPDATE_TASK\`, \`MOVE_TASK\`, \`DELETE_TASK\`, \`REORDER_TASKS\`
- **Persistence**: tasks are serialised to \`localStorage\` on every state change and hydrated on first render
- Consumed via the \`useTasks()\` custom hook

---

## Styling Conventions

| Convention | Details |
|------------|---------|
| **CSS Modules** | Every component has a co-located \`.module.css\` file — zero class-name collisions |
| **Design tokens** | All colours, spacing, typography defined as CSS custom properties in \`globals.css\` |
| **Theming** | Light/dark themes switch by setting \`data-theme\` on \`<html>\` — no JS re-renders needed |
| **No CSS-in-JS** | Keeps bundle lean and styles inspectable in DevTools |

---

## Folder Structure

\`\`\`
src/
├── main/                      ← Electron main process
│   ├── index.js               ← App bootstrap, IPC handlers, BrowserWindow
│   └── preload.js             ← contextBridge API surface
└── renderer/                  ← React application
    ├── main.jsx               ← React DOM entry point
    ├── App.jsx                ← Root layout + theme + modal state
    ├── App.module.css
    ├── components/            ← One folder per component
${components.map(c => `    │   ├── ${c}/`).join('\n')}
    ├── context/
    │   └── TaskContext.jsx    ← Global state (Context + useReducer)
    └── styles/
        └── globals.css        ← Design tokens + CSS reset
\`\`\`

---

## CI/CD Pipeline

See \`.github/workflows/\` for the full pipeline definition.

| Workflow | Trigger | What it does |
|----------|---------|--------------|
| \`ci.yml\` | Push / PR to \`main\` | Lint (ESLint) + Tests (Vitest) + Build check |
| \`release.yml\` | Push of \`v*\` tags | Build installers for macOS / Windows / Linux, create GitHub Release |
| \`update-docs.yml\` | Push to \`main\` (after CI) | Run this script, commit updated \`docs/\` if changed |

---

*Regenerate this file at any time:* \`npm run update-docs\`
`;

  writeFileSync(MD_FILE, md, 'utf8');
  console.log(`✅ Written: docs/architecture.md`);

  console.log(`\n🎉 Docs updated successfully at ${timestamp}`);
}

// ── Run ───────────────────────────────────────────────────────────────────────

try {
  main();
} catch (err) {
  console.error('❌ update-docs failed:', err.message);
  process.exit(1);
}
